name: OpenWrt-CI

on:
  push:
    branches:
      - master
  watch:
    types: started

env:
  SDK_URL: https://downloads.openwrt.org/snapshots/targets/ramips/mt7621/openwrt-sdk-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64.tar.xz
  package_URL: https://github.com/Hey-Leo/GDrcoms.git

jobs:

  Make:

    name: make through SDK

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: 拉取SDK
        run: |
          wget -c $SDK_URL

      - name: 解压
        run: |
          mv *.tar.xz openwrt_SDK.tar.xz
          tar xvf *.tar.xz

      - name: update & install feeds
        run: |
          cd openwrt_SDK
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 正式编译
        run: |
          cd openwrt_SDK
          git clone $package_URL package/mine
          make package/mine/compile

      - name: 准备ipk
        run: |
          cd openwrt_SDK
          mkdir -p ./artifact/package
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/

      - name: 上传ipk
        uses: actions/upload-artifact@main
        with:
          name: package
          path: ./artifact/package/
